### ISSUE TITLE
夜间模式

### ISSUE THREAD

**Issue by chenjingzhang** [hymanme/MaterialHome#4]
为什么我设置的夜间模式  只有在重启应用的时候才生效。点击按钮 并不生效

**Comment by hymanme** [comment]
点击按钮会重启当前activity、然后生效、会自动的，请问你的手机什么系统？

发自我的 iPhone

**Comment by chenjingzhang** [comment]
因为 有很多的activity  然后点击按钮的时候。有的页面变成夜间模式了 有的并没有 只有重启应用 才全部变成夜间模式

**Comment by chenjingzhang** [comment]
就是我点击 按钮的时候 只有当前activity会变成夜间模式。但是 其他的页面基本上都没有变化。只有重启应用的时候才会变化。用的vivo手机

**Comment by hymanme** [comment]
请用模拟器试试。

发自我的 iPhone
